name: gba
description: >
  A GameBoy Advanced emulator written in Dart
version: 0.0.1-dev
authors:
  - Matan Lurey <matan@lurey.org>
  - Kendal Harland <kendaljharland@gmail.com>
homepage: https://github.com/matanlurey/gba.dart/blob/master/gba

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  func: '^0.1.1'
  quiver: '^0.24.0'
  resource: '^2.0.0'

# Required for development. When we publish to pub, we'll comment this out.
dependency_overrides:
  arm7_tdmi:
    path: ../arm7_tdmi

dev_dependencies:
  path: '^1.0.0'
  test: '^0.12.18+1'
